management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, bindings
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: xml-sales-messages
        output:
          destination: all-sales-records
      propagateOriginalContentType: false
    streamapp:
      security:
        enabled: false