management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, bindings
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: json-sales-messages
      propagateOriginalContentType: false
    streamapp:
      security:
        enabled: false