management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  cloud:
    streamapp:
      security:
        enabled: false